{
  "BALANCE": [],
  "STAKESTONE": [],
  "PRICE": [],
  "TRANSFER": [
    {
      "message": "TRANSFER: Missing executions for 3 transaction hashes",
      "timestamp": "2025-06-29T02:19:31.364Z",
      "data": {
        "missingHashes": [
          "0x09f0719119cb6011db60f9e39b4b2f94a2157521da8fdf1bd9404e505aebb85e",
          "0xefef08e063edd61c51292128ea2e516554923320bf957c72aa1eac630b9ef4cd",
          "0x6d00a7d04f63a52d3eebb33ce6482a2c6631022611a7a8b89cc371eaaa987379"
        ],
        "totalComparisonEntries": 20,
        "totalExecutions": 1
      }
    },
    {
      "message": "TRANSFER: Missing executions for 2 transaction hashes",
      "timestamp": "2025-06-29T02:36:59.385Z",
      "data": {
        "missingHashes": [
          "0x9c124cb91128efbe993d6ae8bd6b5cc95d2f38c0cc39d8331fb63d739a557463",
          "0x188d79fef0e65ad2a667719d7b193158082dd2fd68f92edc841bda79b495cdb0"
        ],
        "totalComparisonEntries": 7,
        "totalExecutions": 2
      }
    }
  ],
  "EVERY_PERIOD": [],
  "SERVER": [
    {
      "message": "API Error for /workflows/ec13e853-dc22-4d42-9b76-cba6810d07e6: request to http://localhost:3040/api/workflows/ec13e853-dc22-4d42-9b76-cba6810d07e6 failed, reason: ",
      "timestamp": "2025-06-29T02:37:38.791Z",
      "data": {
        "endpoint": "/workflows/ec13e853-dc22-4d42-9b76-cba6810d07e6",
        "error": "request to http://localhost:3040/api/workflows/ec13e853-dc22-4d42-9b76-cba6810d07e6 failed, reason: ",
        "stack": "FetchError: request to http://localhost:3040/api/workflows/ec13e853-dc22-4d42-9b76-cba6810d07e6 failed, reason: \n    at ClientRequest.<anonymous> (file:///Users/thuanvo/Documents/Work/otomato/status-page/node_modules/node-fetch/src/index.js:108:11)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:512:5)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
      }
    },
    {
      "message": "API Error for /workflows: request to http://localhost:3040/api/workflows failed, reason: ",
      "timestamp": "2025-06-29T02:37:38.794Z",
      "data": {
        "endpoint": "/workflows",
        "error": "request to http://localhost:3040/api/workflows failed, reason: ",
        "stack": "FetchError: request to http://localhost:3040/api/workflows failed, reason: \n    at ClientRequest.<anonymous> (file:///Users/thuanvo/Documents/Work/otomato/status-page/node_modules/node-fetch/src/index.js:108:11)\n    at ClientRequest.emit (node:events:536:35)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:512:5)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
      }
    },
    {
      "message": "API Error for /workflows/af791600-22cc-4929-8254-b351b096078c: request to http://localhost:3040/api/workflows/af791600-22cc-4929-8254-b351b096078c failed, reason: ",
      "timestamp": "2025-06-29T02:37:38.796Z",
      "data": {
        "endpoint": "/workflows/af791600-22cc-4929-8254-b351b096078c",
        "error": "request to http://localhost:3040/api/workflows/af791600-22cc-4929-8254-b351b096078c failed, reason: ",
        "stack": "FetchError: request to http://localhost:3040/api/workflows/af791600-22cc-4929-8254-b351b096078c failed, reason: \n    at ClientRequest.<anonymous> (file:///Users/thuanvo/Documents/Work/otomato/status-page/node_modules/node-fetch/src/index.js:108:11)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:512:5)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
      }
    },
    {
      "message": "API Error for /workflows: request to http://localhost:3040/api/workflows failed, reason: ",
      "timestamp": "2025-06-29T02:37:38.798Z",
      "data": {
        "endpoint": "/workflows",
        "error": "request to http://localhost:3040/api/workflows failed, reason: ",
        "stack": "FetchError: request to http://localhost:3040/api/workflows failed, reason: \n    at ClientRequest.<anonymous> (file:///Users/thuanvo/Documents/Work/otomato/status-page/node_modules/node-fetch/src/index.js:108:11)\n    at ClientRequest.emit (node:events:536:35)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:512:5)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
      }
    },
    {
      "message": "API Error for /workflows/7ed8a26a-c4cb-44ff-8eae-260a51a80d86: request to http://localhost:3040/api/workflows/7ed8a26a-c4cb-44ff-8eae-260a51a80d86 failed, reason: ",
      "timestamp": "2025-06-29T02:37:38.800Z",
      "data": {
        "endpoint": "/workflows/7ed8a26a-c4cb-44ff-8eae-260a51a80d86",
        "error": "request to http://localhost:3040/api/workflows/7ed8a26a-c4cb-44ff-8eae-260a51a80d86 failed, reason: ",
        "stack": "FetchError: request to http://localhost:3040/api/workflows/7ed8a26a-c4cb-44ff-8eae-260a51a80d86 failed, reason: \n    at ClientRequest.<anonymous> (file:///Users/thuanvo/Documents/Work/otomato/status-page/node_modules/node-fetch/src/index.js:108:11)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:512:5)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
      }
    },
    {
      "message": "API Error for /workflows: request to http://localhost:3040/api/workflows failed, reason: ",
      "timestamp": "2025-06-29T02:37:38.802Z",
      "data": {
        "endpoint": "/workflows",
        "error": "request to http://localhost:3040/api/workflows failed, reason: ",
        "stack": "FetchError: request to http://localhost:3040/api/workflows failed, reason: \n    at ClientRequest.<anonymous> (file:///Users/thuanvo/Documents/Work/otomato/status-page/node_modules/node-fetch/src/index.js:108:11)\n    at ClientRequest.emit (node:events:536:35)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:512:5)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
      }
    },
    {
      "message": "API Error for /workflows/c4eaf1d8-4786-478e-9051-54d447ad97e4: request to http://localhost:3040/api/workflows/c4eaf1d8-4786-478e-9051-54d447ad97e4 failed, reason: ",
      "timestamp": "2025-06-29T02:37:38.803Z",
      "data": {
        "endpoint": "/workflows/c4eaf1d8-4786-478e-9051-54d447ad97e4",
        "error": "request to http://localhost:3040/api/workflows/c4eaf1d8-4786-478e-9051-54d447ad97e4 failed, reason: ",
        "stack": "FetchError: request to http://localhost:3040/api/workflows/c4eaf1d8-4786-478e-9051-54d447ad97e4 failed, reason: \n    at ClientRequest.<anonymous> (file:///Users/thuanvo/Documents/Work/otomato/status-page/node_modules/node-fetch/src/index.js:108:11)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:512:5)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
      }
    },
    {
      "message": "API Error for /workflows: request to http://localhost:3040/api/workflows failed, reason: ",
      "timestamp": "2025-06-29T02:37:38.804Z",
      "data": {
        "endpoint": "/workflows",
        "error": "request to http://localhost:3040/api/workflows failed, reason: ",
        "stack": "FetchError: request to http://localhost:3040/api/workflows failed, reason: \n    at ClientRequest.<anonymous> (file:///Users/thuanvo/Documents/Work/otomato/status-page/node_modules/node-fetch/src/index.js:108:11)\n    at ClientRequest.emit (node:events:536:35)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:512:5)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
      }
    },
    {
      "message": "API Error for /workflows/09134aeb-e3bc-45d0-ba45-88b0afd169a1: request to http://localhost:3040/api/workflows/09134aeb-e3bc-45d0-ba45-88b0afd169a1 failed, reason: ",
      "timestamp": "2025-06-29T02:37:38.809Z",
      "data": {
        "endpoint": "/workflows/09134aeb-e3bc-45d0-ba45-88b0afd169a1",
        "error": "request to http://localhost:3040/api/workflows/09134aeb-e3bc-45d0-ba45-88b0afd169a1 failed, reason: ",
        "stack": "FetchError: request to http://localhost:3040/api/workflows/09134aeb-e3bc-45d0-ba45-88b0afd169a1 failed, reason: \n    at ClientRequest.<anonymous> (file:///Users/thuanvo/Documents/Work/otomato/status-page/node_modules/node-fetch/src/index.js:108:11)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:512:5)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
      }
    },
    {
      "message": "API Error for /workflows: request to http://localhost:3040/api/workflows failed, reason: ",
      "timestamp": "2025-06-29T02:37:38.810Z",
      "data": {
        "endpoint": "/workflows",
        "error": "request to http://localhost:3040/api/workflows failed, reason: ",
        "stack": "FetchError: request to http://localhost:3040/api/workflows failed, reason: \n    at ClientRequest.<anonymous> (file:///Users/thuanvo/Documents/Work/otomato/status-page/node_modules/node-fetch/src/index.js:108:11)\n    at ClientRequest.emit (node:events:536:35)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:512:5)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
      }
    }
  ]
}